# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: false
cache:
  - packages: true
  - apt: false

env:
  - NOT_CRAN=true
  
notifications:
  slack: fitzroy-rafl:f7fzevoXtmES8g2kGLspLWK1

#r_build_args: '--no-build-vignettes'
#r_check_args: '--as-cran --ignore-vignettes'  

r:

- 3.3
- 3.4
- 3.5
- 3.6
- 4.0
- release
- devel

# workaround for breaking issue with markdown
r_github_packages: rstudio/rmarkdown

after_success:
  - Rscript -e 'covr::codecov()'

script: 
  - |
    R CMD build .
    travis_wait 20 R CMD check fitzRoy*tar.gz
